### ISSUE TITLE
Remove unsplash and pixabay

### ISSUE THREAD

**Issue by hydrargyrum** [heyalexej/awesome-images#60]
They do not offer public domain or CC0 anymore, just regular no-commercial-use licenses. They pretend to, but their license text is clear that it's not, see https://unsplash.com/license and https://pixabay.com/service/license/

**Comment by cblte** [comment]
I agree to the cc0 license type. But would not remove them from the list as they still offer a Free Images formprivate and commercial use. The license says you are not allowed to sell unaltered images. But it also does not prohibit to alter. So when you alter you can sell and upload them to other platforms. Still ok for a lot of people. 

TLDR: instead of removing the links, update the Description.
